{% set name = "ddtrace" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ddtrace-{{ version }}.tar.gz
  sha256: 986f7a51c7d0b234e23b800f096d84a2ec298ad13655ecf672e08392500109f6

build:
  number: 1
  entry_points:
    - ddtrace-run = ddtrace.commands.ddtrace_run:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - cython
    - python
    - pip
    - setuptools_scm[toml] >=4,<6.1
  run:
    - python
    - pip
    - protobuf
    - tenacity >=5
    - packaging >=17.1
    - attrs >=19.2.0
    - six >=1.12.0
    - ddsketch >=2.0.1

test:
  imports:
    - ddtrace
    - ddtrace.bootstrap
  requires:
    - pip
  commands:
    - pip check
  

about:
  home: https://github.com/DataDog/dd-trace-py
  summary: Datadog APM client library
  license: BSD-3-Clause
  license_file: LICENSE.BSD3

extra:
  recipe-maintainers:
    - aymondebroglie
    - SarvarD
