{% set name = "ddtrace" %}
{% set version = "0.46.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ddtrace-{{ version }}.tar.gz
  sha256: 73c43ddfcf8cc2dc2d31bfd5367fad83820a37ec5a9493fbd009681cc9328eba

build:
  number: 0
  skip: true  # [py==30 or py==31 or py==32 or py==33 or py==34]
  entry_points:
    - ddtrace-run = ddtrace.commands.ddtrace_run:main
    - pyddprofile = ddtrace.profiling.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
    - setuptools_scm >=4
  run:
    - python
    - pip
    - enum34  # [py<34]
    - funcsigs >=1.0.0  # [py==27]
    - typing  # [py<35]
    - intervaltree
    - protobuf >=3
    - tenacity >=5

test:
  imports:
    - ddtrace
    - ddtrace.bootstrap
  requires:
    - tox
    - flake8

about:
  home: https://github.com/DataDog/dd-trace-py
  summary: Datadog tracing code
  license: BSD-3-Clause
  license_file: LICENSE.BSD3

extra:
  recipe-maintainers:
    - aymondebroglie
    - SarvarD
